import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
import { workspace, fixture, until } from '../helpers.js';

const temp = workspace('bps-gui-');
const site = await fixture();
const { startServer } = await import('../../src/server.js');
const runtime = await startServer({ port: 0 });
const browser = await chromium.launch({ channel: 'chromium', headless: true });
const context = await browser.newContext({ viewport: { width: 1365, height: 900 }, colorScheme: 'light' });
const page = await context.newPage();
page.setDefaultTimeout(10000);
const errors = [];
let exportedProfiles;
page.on('pageerror', error => errors.push(error.message));
const screenshots = path.resolve('test-results'); fs.mkdirSync(screenshots, { recursive: true });
after(async () => { await browser.close(); await runtime.stop(); await site.close(); temp.remove(); });

test('GUI：创建 JSON 任务、配置两个独立 Profile、并发运行、进度、产物和 MCP 配置', { timeout: 90000 }, async () => {
  await page.goto(runtime.origin);
  await page.locator('#connDot.online').waitFor();
  await page.getByRole('tab', { name: '任务脚本', exact: true }).click();
  await page.locator('#newTaskBtn').click();
  await page.locator('#taskJson').fill(JSON.stringify({ id: 'gui-task', name: '页面检查', steps: [{ action: 'unknown' }] }));
  await page.locator('#saveTaskBtn').click();
  await until(() => page.locator('#taskEditorError').textContent());
  assert.equal(await page.locator('#taskEditor').isVisible(), true);
  const task = { id: 'gui-task', name: '页面检查', description: '读取当前页面并保存截图。', steps: [{ action: 'open', url: '{{url}}' }, { action: 'read', saveAs: 'page' }, { action: 'screenshot', name: 'page.png' }] };
  await page.locator('#taskJson').fill(JSON.stringify(task, null, 2));
  await page.locator('#saveTaskBtn').click();
  await page.locator('#taskEditor').waitFor({ state: 'hidden' });
  await page.getByRole('tab', { name: '实例管理' }).click();
  for (const [name, prompt] of [['研究工作区', '研究提示词'], ['独立会话', '独立提示词']]) {
    await page.locator('#addProfileBtn').click();
    await page.locator('#pfName').fill(name); await page.locator('#pfUrl').fill(site.url);
    await page.locator('#pfTask').selectOption('gui-task'); await page.locator('#pfPrompt').fill(prompt);
    await page.locator('#pfHeadless').check(); await page.locator('#drawerSave').click();
    await page.locator('#drawer').waitFor({ state: 'hidden' });
    await page.locator('.profile-card').filter({ hasText: name }).waitFor();
  }
  assert.equal(await page.locator('.profile-card').count(), 2);
  const profileResponse = await fetch(`${runtime.origin}/api/profiles`);
  const profiles = await profileResponse.json();
  assert.equal(profiles[0].prompt, '研究提示词'); assert.equal(profiles[1].prompt, '独立提示词');
  assert.notEqual(profiles[0].userDataDir, profiles[1].userDataDir);
  await until(async () => await page.locator('.toast').count() === 0);
  await page.screenshot({ path: path.join(screenshots, 'gui-profiles.png'), fullPage: true, animations: 'disabled' });
  await page.locator('#selectAll').check(); await page.locator('#batchRunBtn').click();
  await page.locator('#view-run.is-active').waitFor();
  await until(async () => await page.locator('.run-row[data-status="success"]').count() === 2, 25000);
  assert.equal(await page.locator('#runTask').inputValue(), '');
  await page.screenshot({ path: path.join(screenshots, 'gui-run.png'), fullPage: true, animations: 'disabled' });
  await page.locator('[data-run-detail]').first().click();
  await page.locator('#runResultPreview').waitFor();
  assert.match(await page.locator('#runResultPreview').textContent(), /Automation Fixture/);
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('link', { name: 'page.png', exact: true }).click();
  const download = await downloadPromise; assert.equal(download.suggestedFilename(), 'page.png');
  await page.locator('[data-close-dialog="runDetail"]').click();
  await page.getByRole('tab', { name: '实例管理' }).click();
  await page.locator('[data-act="more"]').first().click();
  await page.getByRole('button', { name: '连接 Playwright MCP', exact: true }).click();
  await page.locator('#mcpDialog').waitFor();
  const config = JSON.parse(await page.locator('#mcpConfig').inputValue());
  assert.match(Object.values(config.mcpServers)[0].url, /\/mcp\/[0-9a-f]{12}$/);
  await page.locator('[data-close-dialog="mcpDialog"]').click();
  await page.getByRole('tab', { name: '日志中心', exact: true }).click();
  await page.locator('#logProfile').selectOption(profiles[0].id);
  assert.ok(await page.locator('.log-line').count() > 0);
  assert.doesNotMatch(await page.locator('#logBox').textContent(), /独立会话/);
  assert.deepEqual(errors, []);
});

test('工作台：筛选全选、实时预览、批量停止、代理与配置导出', { timeout: 45000 }, async () => {
  await page.getByRole('tab', { name: '实例管理' }).click();
  await page.locator('#selectAll').uncheck();
  await page.locator('#profileSearch').fill('研究');
  assert.equal(await page.locator('.profile-card').count(), 1);
  await page.locator('#selectAll').check();
  assert.equal(await page.locator('#selectedCount').textContent(), '已选 1 个');
  await page.locator('#profileSearch').fill('不存在的实例');
  assert.equal(await page.locator('#noMatches').isVisible(), true);
  await page.locator('#resetFiltersBtn').click();
  await page.locator('#selectAll').check();
  await page.locator('#batchLaunchBtn').click();
  await until(async () => (await page.locator('.pc-status').allTextContents()).every(s => s.includes('运行中')), 20000);
  await until(async () => await page.locator('.pc-preview img:not([hidden])').count() === 2, 15000);
  assert.equal(await page.locator('.preview-hint:not([hidden])').first().textContent(), '实时预览 · 点击进入');
  await page.locator('#previewEnabled').uncheck();
  assert.equal(await page.locator('.preview-hint:not([hidden])').first().textContent(), '预览已暂停');
  await page.locator('#previewEnabled').check();
  await until(async () => (await page.locator('.preview-hint:not([hidden])').first().textContent()).includes('实时预览'));
  await until(async () => (await page.locator('#memoryValue').textContent()).includes('GB'));
  assert.equal(await page.locator('#view-profiles').isVisible(), true);
  await page.screenshot({ path: path.join(screenshots, 'gui-workspace-live.png'), fullPage: true, animations: 'disabled' });
  const downloadReady = page.waitForEvent('download');
  await page.locator('#exportProfilesBtn').click();
  const exported = await downloadReady;
  assert.equal(exported.suggestedFilename(), 'browser-play-set-profiles.json');
  exportedProfiles = fs.readFileSync(await exported.path());
  await page.locator('#batchStopBtn').click();
  await until(async () => (await page.locator('.pc-status').allTextContents()).every(s => s.includes('已停止')), 15000);
  assert.equal(await page.locator('.pc-preview img:not([hidden])').count(), 0);
  await page.getByRole('tab', { name: '代理管理', exact: true }).click();
  assert.equal(await page.locator('#proxyTableBody tr').count(), 2);
  await page.locator('[data-edit-proxy]').first().click();
  assert.equal(await page.locator('#drawer').isVisible(), true);
  await page.keyboard.press('Escape');
  assert.deepEqual(errors, []);
});

test('工作台：配置导出后可预览并导入为全新实例', { timeout: 15000 }, async () => {
  await page.getByRole('tab', { name: '实例管理' }).click();
  const before = await (await fetch(`${runtime.origin}/api/profiles`)).json();
  await page.locator('#importProfilesFile').setInputFiles({ name: 'profiles.json', mimeType: 'application/json', buffer: exportedProfiles });
  await page.locator('#importProfilesDialog').waitFor();
  assert.equal(await page.locator('#importProfilesList li').count(), 2);
  await page.locator('#confirmImportProfilesBtn').click();
  await page.locator('#importProfilesDialog').waitFor({ state: 'hidden' });
  await until(async () => await page.locator('.profile-card').count() === 4);
  const after = await (await fetch(`${runtime.origin}/api/profiles`)).json();
  assert.equal(new Set(after.map(p => p.userDataDir)).size, 4);
  assert.deepEqual(after.slice(0, 2).map(p => p.id), before.map(p => p.id));
  assert.deepEqual(errors, []);
});

test('GUI：移动视口、深色主题和键盘关闭编辑器', { timeout: 20000 }, async () => {
  await page.getByRole('tab', { name: '实例管理' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.mouse.move(0, 0);
  await page.screenshot({ path: path.join(screenshots, 'gui-mobile.png'), fullPage: true, animations: 'disabled' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await page.locator('#addProfileBtn').click(); await page.keyboard.press('Escape');
  assert.equal(await page.locator('#drawer').isVisible(), false);
  await page.setViewportSize({ width: 1365, height: 900 });
  await page.locator('#themeToggle').click();
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
  await page.screenshot({ path: path.join(screenshots, 'gui-dark.png'), fullPage: true, animations: 'disabled' });
  assert.deepEqual(errors, []);
});
